# Generated by Django 3.2.6 on 2021-08-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20210830_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='id_alum',
            new_name='id_alumno',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='id_cur',
            new_name='id_curso',
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(verbose_name=2)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
            ],
        ),
    ]
