# Generated by Django 3.2.6 on 2021-08-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_auto_20210830_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
