# Generated by Django 3.2.7 on 2021-09-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='profile',
            field=models.FileField(max_length=30, upload_to=''),
        ),
    ]
