# Generated by Django 3.2.8 on 2021-10-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=50)),
                ('perfil', models.CharField(max_length=4)),
                ('descripcion', models.CharField(max_length=80)),
                ('cod_usuario', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=15)),
                ('apellidos_nombres', models.CharField(max_length=80)),
            ],
        ),
    ]
